### ISSUE TITLE
Add testing for a complete add/get cycle

### ISSUE THREAD

**Issue by awnumar** [libeclipse/pocket#16]
Current testing for the `crypto` module simply tests the individual functions separately. While good, this isn't the best practice.

What we should be doing [instead of|in addition to] that is having a full test cycle for adding and retrieving an entry. The test would add and retrieve an entry (no disk writes) and compare all the values with what they should be.

This will ensure that a build does not accidentally break reverse compatibility.

**Comment by tobbbles** [comment]
What you're talking about here is an integration test. These are easily do-able, and will be even easier to write with the store interface in #13.

**Comment by awnumar** [comment]
The tests as a whole need a full re-write at this point. This is on the agenda for `v0.1.0` after #33 is handled.
