### ISSUE TITLE
Windows Continuous Integration

### ISSUE THREAD

**Issue by awnumar** [libeclipse/pocket#21]
We're currently using Travis-CI for testing on Linux, we can extend this to test OSX too.

However, Travis does not support Windows, although it's been in the works for a few years now. We need to find an alternative. There's Tea-CI but I can't find anyone talking about it and its interface seems kind of basic.

Any suggestions would be great.

**Comment by takhlaq** [comment]
https://github.com/integrations/appveyor

**Comment by awnumar** [comment]
@takhlaq Oh nice. I'll have a look when I get home.
