### ISSUE TITLE
Tagged releases and changelog

### ISSUE THREAD

**Issue by baimafeima** [libeclipse/pocket#49]
Could you tag your releases and make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by awnumar** [comment]
Thanks for the comment.

As you can probably tell, this project is not currently under active development, and it is pre-v0.1.0 anyways. My university term-time has just started and so I am quite short on time, but I do plan on getting back to it soon.

When the project is ready for a first release, I will definitely follow those recommendations, as I already do with my other active projects.
